package:
  create:
    architecture: amd64
    set:
      # The image reference to use for the Zarf agent, defaults to a locally built image
      agent_image_domain: registry1.dso.mil/
      agent_image: ironbank/opensource/zarf-dev/zarf/zarf-agent
      # renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/zarf-dev/zarf/zarf-agent
      agent_image_tag: v0.64.0

      # The image reference to use for the registry that Zarf deploys into the cluster
      registry_image_domain: registry1.dso.mil/
      registry_image: ironbank/opensource/docker/registry-v3
      # renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/docker/registry-v3
      registry_image_tag: 3.0.0

      # renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/go-gitea/gitea
      gitea_image: "registry1.dso.mil/ironbank/opensource/go-gitea/gitea:v1.24.6"
