package:
  create:
    architecture: amd64
    set:
      # The image reference to use for the Zarf agent, defaults to a locally built image
      agent_image_domain: registry1.dso.mil/
      agent_image: ironbank/opensource/defenseunicorns/zarf/zarf-agent
      # renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/defenseunicorns/zarf/zarf-agent
      agent_image_tag: v0.41.0

      # Tag for the zarf injector binary to use
      injector_version: "2024-10-03"
      injector_amd64_shasum: 71b00b2c196ad392acecf691ac72e5d77278d4cfd49554dc3f5c8616c6987437
      injector_arm64_shasum: f9b0765c4bb2b82fae050d3fb25f6f2a2390d7fdcc1533fc46d3c38f0ad83f95

      # The image reference to use for the registry that Zarf deploys into the cluster
      registry_image_domain: ""
      registry_image: library/registry
      # renovate: datasource=docker depName=docker.io/library/registry versioning=loose
      registry_image_tag: 3.0.0-beta.1

      # renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/go-gitea/gitea
      gitea_image: "registry1.dso.mil/ironbank/opensource/go-gitea/gitea:v1.22.2"
