{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: {{ template "docker-registry.serviceAccountName" . }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end -}}
