# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Title Check

on:
  pull_request:
    branches: [main]
    # milestoned is added here so that a PR can be re-triggered if it is milestoned.
    types: [milestoned, opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@f96b0f22cd24e4e7e682184cfa502715fa65708d # v1.27.1
