# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Title Check

on:
  pull_request:
    branches: [main]
    # milestoned is added here so that a PR can be re-triggered if it is milestoned.
    types: [milestoned, opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@90a7222466f9853404c07c5632f1f5ced97f0093 # v1.27.2
