# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Title Check

on:
  pull_request:
    branches: [main]
    # Milestoning supports manual reruns.
    types: [milestoned, opened, reopened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@db5e7c9e48d6c46c0e9b3524349a0d3ca6c538e0 # v1.30.0
