# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Lint

on:
  pull_request:
    branches: [main]
    # milestoned is added here so that a PR can be re-triggered if it is milestoned.
    types: [milestoned, opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-lint.yaml@d940b16c44821fe7a84b7725bdadf7d4fa541c8f # v1.28.1
    secrets: inherit
