# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Lint

on:
  pull_request:
    branches: [main]
    # Milestoning supports manual reruns.
    types: [milestoned, opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-lint.yaml@a99629a47585162e7a133c6f58c9874268103155 # v1.28.3
    secrets: inherit

  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: defenseunicorns/setup-uds@d6add59d4c2ca789ed7c92741e91bd340b4e950b # v1.0.2
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.37.0

      - name: Generate Zarf values schemas
        run: uds run generate-zarf-values-schemas --no-progress

      - name: Verify generated Zarf values schemas
        run: git diff --exit-code -- 'packages/*/zarf-values.schema.json'

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure
